# Guess the output of each answer before you click RUN
# Try to write down your answer before and see how you do... keep it mind I made it a little tricky for you :)

print("Guess:")
print("45")
print("Result:")
print((5 + 4) * 10 / 2)
print("\n")
print("Guess:")
print("45")
print("Result:")
print(((5 + 4) * 10) / 2)
print("\n")
print("Guess:")
print("45")
print("Result:")
print((5 + 4) * (10 / 2))
print("\n")
print("Guess:")
print("25")
print("Result:")
print(5 + (4 * 10) / 2)
print("\n")
print("Guess:")
print("25")
print("Result:")
print(5 + 4 * 10 // 2)